# Generated by Django 4.2.5 on 2024-05-22 14:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('phn', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('c_img', models.ImageField(blank=True, null=True, upload_to='cov_prof_images')),
                ('since', models.DateField(blank=True, default='2024-02-25', null=True)),
                ('insta_link', models.URLField(blank=True, max_length=255, null=True)),
                ('linked_link', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_det', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover_images')),
                ('posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('likes', models.ManyToManyField(related_name='blog_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
